### ISSUE TITLE
Inconsistent/intransparent score definitions

### ISSUE THREAD

**Issue by NMertsch** [j-andrews7/pytfmpval#2]
```python
# example from README
from pytfmpval import tfmp
mat = (" 3  7  9  3 11 11 11  3  4  3  8  8  9  9 11  2"
       " 5  0  1  6  0  0  0  3  1  4  5  1  0  5  0  7"
       " 4  3  1  4  3  2  2  2  8  6  1  4  2  0  3  0"
       " 2  4  3  1  0  1  1  6  1  1  0  1  3  0  0  5"
      )
m = tfmp.read_matrix(mat)
print(tfmp.pval2score(m, 0.00001))  # 8.773708000000001
print(tfmp.score2pval(m, 8.7737))  # 9.992625564336777e-06

# my addition
print(m.minScore)  # 0
print(m.maxScore)  # 435430296
```

The cited paper defines the score as the sum of one element per column (representing the nucleotides).

1. the minimal score of the matrix cannot be zero, as there are multiple columns which do not contain a zero. It is 10 (`2+0+1+1+0+0+0+2+1+1+1+1+0+0+0+0`).
2. the maximal score cannot be 4.35e8, it is 132 (`5+7+9+6+11+11+11+6+8+6+8+8+9+9+11+7`)
3. the score result of `pval2score` obviously is a different kind of score as the one given by `m.minScore` and `m.maxScore` and also different from the definition in the paper.

Can someone please clarify on the score definitions?

**Comment by j-andrews7** [comment]
A few comments that might help clarify:

1. The scores are not derived from count matrices. Any such matrices containing simple counts are transformed into a log-ratio matrix containing a pseudocount. This addresses your points 1 & 2 (to an extent).

2. As for your third point, it's the same type of score. The minScore and maxScore are the endpoints of a score distribution determined by internal functions (the original authors had functions for this that were externally exposed, but I didn't particularly care about look at the distribution itself, so I did not rewrite/wrap those functions in my C extension). The `pval2score` function returns the score from that distribution that corresponds to the input p-value (and vice-versa).

My background is not in math, so my understanding doesn't extend a whole lot further than this. Contacting the original authors might be worth your while if you have more specific questions. I've also attached the [README](https://github.com/j-andrews7/pytfmpval/files/3142898/ReadMe.txt) for the original program, which has a little bit of info that relates to your question. Reading the [docs](https://pytfmpval.readthedocs.io/en/latest/#full-tfmp-module-reference) for the specific functions may also help.

**Comment by NMertsch** [comment]
Thanks for the answer, I will look into that.

My actual problem is, that I have a matrix and sequences, want to compute a score for each sequence and get the p-value for that score. Sadly I am not able to reproduce the kind of score that this package expects.

If I find an answer, I will let you know.

**Comment by j-andrews7** [comment]
The scores are just log-odds ratios - you can calculate them for a sequence and matrix fairly easily. First, you need to generate a [position weight matrix](https://en.wikipedia.org/wiki/Position_weight_matrix) for your matrix from the counts. This is done by converting the counts for each base at each position to frequencies and taking the natural log (or log2, `pytfmpval` supports either, I'll use log2 in this case) I'll use a limited form of example matrix above - rows are bases (A, C, G, T), columns are positions:

```
# Set background frequencies for each - chance of any given position containing a given base.
bg = [0.25, 0.25, 0.25, 0.25]

# Initialize the matrix.
mat = ([3,  7,  9,  3, 11],
       [5,  0,  1,  6,  0],
       [4,  3,  1,  4,  3],
       [2,  4,  3,  1,  0],
      )

# For clarity. A list for each base.
a = mat[0]
c = mat[1]
g = mat[2]
t = mat[3]

# Initialize output matrix of same size as input matrix.
pwm = [[0 for y in range(length(a)] for x in range(4)]

# Divide each position by the sum of its column (14 in this case, will often be much higher).
for pos in range(length(a)):
            total = float(a[pos]) + float(c[pos]) + float(g[pos]) + float(t[pos])
            # Using a pseudocount to account for positions with 0, as noted.
            total += 4 * 1
            # Actually calculate the log-odds of the base for the matrix.
            for base in range(4):
                pwm[base][pos] = log2((float(mat[base][pos]) + 1) / total) - log2(background[base])
```

Okay, so now we have a position weight matrix (`pwm`) with the frequency of each base at each position derived from our count matrix. Now we can score any given sequence of the same length against that PWM:

```
sequence = "CGTAC"
score = 0

for pos in range(length(a)):
    # Match base: compute score for each position
    if (sequence[pos] == 'A'):
        score += pwm[0][pos]
    elif (sequence[pos] == 'C'):
         score += pwm[1][pos]
    elif (sequence_str[pos] == 'G'):
         score += pwm[2][pos]
    elif (sequence_str[pos] == 'T'):
         score += pwm[3][pos]
```

You can then use this score and matrix with `pytfmpval` to derive a p-value for the score. I made this package for scanning the impact of variants on motifs, so I used it to set threshold scores for each motif matrix for determining whether a sequence was actually a match to the motif or not. Then I measured how the variant impacted the motif score compared to the reference sequence and how the p-value changed.

I hope that helps.

**Comment by j-andrews7** [comment]
I'm going to close this, but just comment if you have other questions.
